# Generated by Django 5.2.4 on 2025-09-25 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_initial'),
        ('posts', '0003_remove_post_image_url_post_image_post_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'post'], name='interaction_user_id_4d6132_idx'),
        ),
    ]
